import argparse


def get_options(args=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--learning_rate", type=float, default=1e-3)
    parser.add_argument("--batch_size", type=int, default=512)
    parser.add_argument("--num_epoch", type=float, default=1500)
    parser.add_argument("--in_dim", type=int, default=16)
    parser.add_argument("--out_dim", type=int, default=256)
    parser.add_argument("--hidden_dim", type=int, default=256)
    parser.add_argument("--out_nlayers", type=int,default=2)
    parser.add_argument("--in_nlayers", type=int,default=2)
    parser.add_argument("--gcn_dropout", type=float, default=0)
    parser.add_argument("--mlp_dropout", type=float, default=0)
    parser.add_argument("--weight_decay", type=float, default=0)
    parser.add_argument("--model_saving_dir", type=str, default='model')
    parser.add_argument("--pre_model_dir",type=str,default='model')
    parser.add_argument("--preprocess",action='store_true')
    parser.add_argument("--n_fcn",type=int,default=3)
    parser.add_argument("--alpha",type=float,default=1.0)
    parser.add_argument("--pre_train",action='store_true')
    parser.add_argument("--change_lr",action='store_true')
    parser.add_argument("--change_alpha",action='store_true',)
    parser.add_argument("--gpu",type=int,default=0)
    parser.add_argument('--balanced',action='store_true',help = 'choose to balance the training dataset')
    parser.add_argument('--gat',action='store_true',help = 'choose a GAT-based model')
    parser.add_argument('--label',type=str,default='in')
    parser.add_argument('--gin',action='store_true')
    parser.add_argument('--abgnn',action='store_true')
    parser.add_argument('--sage', action='store_true')
    parser.add_argument('--include',action='store_true')
    parser.add_argument('--nlabels',type=int,default=2)
    parser.add_argument('--os_rate',type=int,default=20)
    parser.add_argument('--beta',type=float,default=0.5,help='choose the threshold for binary classification to make a trade-off between recall and precision')
    parser.add_argument('--function',action='store_true')
    parser.add_argument('--datapath',type=str,default='data/boundary')
    parser.add_argument('--num_input', type=int, default=2)
    parser.add_argument('--ntypes',type=int,default=16)
    parser.add_argument('--train_percent',type=float,default=6)

    options = parser.parse_args(args)

    return options
